## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - APP-FUNC-TEST
  # - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

variables: 
  utils_path: "/builds/openebs/e2e-mayastor/utils"

# Setup the kubernetes cluster

cluster-setup:
  image: ranjnshashank855/gcp-runner:v1
  stage: CLUSTER-SETUP 
  tags: 
    - mayastor
  script:
    - chmod 775 ./pipelines/1-cluster-setup/cluster-setup
    - ./pipelines/1-cluster-setup/cluster-setup
  artifacts:
    paths:
      - .kube/

## Setup OpenEBS control plane

mayastor-deploy:
  image: ranjnshashank855/gcp-runner:v1
  stage: PROVIDER-INFRA-SETUP
  tags: 
    - mayastor
  dependencies:
    - cluster-setup
  script: 
   - chmod 775 ./pipelines/2-providers/mayastor-provision
   - ./pipelines/2-providers/mayastor-provision

## Define a job template for app deployers

.app_deploy_template:
  image: openebs/openshift-ci:latest
  stage: APP-FUNC-TEST
  tags: 
    - mayastor
  dependencies:
    - cluster-setup

fio-deploy:
  extends: .app_deploy_template
  script:
    - chmod 775 ./pipelines/3-functional/apps/fio-deploy
    - ./pipelines/3-functional/apps/fio-deploy
   
## Define the app deployer jobs

cluster-cleanup:
  when: always
  image: ranjnshashank855/gcp-runner:v1
  stage: CLUSTER-CLEANUP
  tags: 
    - mayastor
  script: 
    - chmod 775 ./pipelines/5-cleanup/cluster-cleanup
    - ./pipelines/5-cleanup/cluster-cleanup