## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - PROVIDER-INFRA-SETUP
  - APP-FUNC-TEST
  # - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

# Setup the kubernetes cluster

cluster-setup:
  image: ranjnshashank855/gke:v1
  stage: CLUSTER-SETUP 
  script:
    - chmod 775 ./pipelines/1-cluster-setup/cluster-setup
    - ./pipelines/1-cluster-setup/cluster-setup
  artifacts:
    paths:
      - .kube/

## Setup OpenEBS control plane

mayastor-deploy:
  image: openebs/openshift-ci:latest
  stage: PROVIDER-INFRA-SETUP
  dependencies:
    - cluster-setup
  script: 
   - echo "Deploying MayaStor"

## Define a job template for app deployers

.app_deploy_template:
  image: openebs/openshift-ci:latest
  stage: APP-FUNC-TEST
  dependencies:
    - cluster-setup

fio-deploy:
  extends: .app_deploy_template
  script: 
   - echo "Deploying fio using MayaStor"
## Define the app deployer jobs

cluster-cleanup:
  when: always
  image: ranjnshashank855/gke:v1
  dependencies:
    - cluster-setup
  stage: CLUSTER-CLEANUP
  script: 
    - chmod 775 ./pipelines/5-cluster-cleanup/cluster-cleanup
    - ./pipelines/5-cluster-cleanup/cluster-cleanup