#!/bin/bash
set -e

present_dir=$(pwd)
echo $present_dir

git clone https://github.com/mayadata-io/litmus.git

cd litmus/k8s/gke/k8s-installer

echo $SDK_TOKEN > key.json

gcloud auth activate-service-account --key-file=./key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="./key.json"
export GCP_SERVICE_ACCOUNT_FILE="./key.json"
export GKEUSER=`echo $GKE_USER`

ls

sed -i -e 's/no_log: True/ /g' create-gke-cluster.yml

echo "creating cluster"

ansible-playbook create-gke-cluster.yml -vv


mkdir $present_dir/.kube
cat ~/.kube/config > $present_dir/.kube/config
cat ~/.kube/config > $present_dir/.kube/admin.conf
cat ~/logs/clusters > $present_dir/.kube/clusters
cat ~/logs/zone > $present_dir/.kube/zone

kubectl get nodes
kubectl apply -f $present_dir/litmus/hack/rbac.yaml
kubectl apply -f $present_dir/litmus/hack/crds.yaml
kubectl create configmap kubeconfig --from-file=$present_dir/.kube/admin.conf -n litmus