#!/bin/bash
set -e

present_dir=$(pwd)
echo $present_dir

git clone https://github.com/mayadata-io/litmus.git

cd litmus/k8s/gcp/k8s-installer/

echo $SDK_TOKEN > key.json

gcloud auth activate-service-account --key-file=./key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="./key.json"

ls

echo "Creating VPC"

ansible-playbook create-vpc.yml --extra-vars "project=openebs-ci" -vv

echo "creating cluster"
sed -i 's/ubuntu-1604-xenial-v20170202/ubuntu-1804-bionic-v20191021/g' create-k8s-cluster.yml
ansible-playbook create-k8s-cluster.yml -vv --extra-vars "project=openebs-ci nodes=3 k8s_version=1.14.0"

mkdir $present_dir/.kube
cat ~/.kube/config > $present_dir/.kube/config
cat ~/.kube/config > $present_dir/.kube/admin.conf
cat ~/logs/clusters > $present_dir/.kube/clusters
cat ~/logs/vpc > $present_dir/.kube/vpc

echo "****Cluster Availability****"
set +e
for i in {1..40}
do
  kubectl get nodes
  if [ "$?" == "0" ]; then
   break;
  else
   sleep 30;
  fi
done

set -e

echo "******Checking for the number of nodes in ready state******"
for i in {1..10}
do 
  ready_nodes=$(kubectl get nodes | grep Ready | wc -l)
  if [ "$ready_nodes" -eq 4 ]; then
     echo "Number of nodes in ready state is $ready_nodes"
  else
    sleep 30;
  fi
done

echo "Attching disks to each of then nodes"

echo $SDK_TOKEN > key.json

cd ../gpd-disks
sed -i 's/us-central1-a/us-east1-b/g' create-gpd.yml
sed -i 's/20/50/g' create-gpd.yml

ansible-playbook create-gpd.yml --extra-vars "json=key.json email=$service_account_email project=openebs-ci" -vv

kubectl get nodes
kubectl apply -f $present_dir/litmus/hack/rbac.yaml
kubectl apply -f $present_dir/litmus/hack/crds.yaml