#!/bin/bash

set -e

present_dir=$(pwd)
echo $present_dir

echo "cleanup"
mkdir ~/logs
cp .kube/clusters ~/logs
cp .kube/vpc ~/logs

git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/gcp/k8s-installer/

echo $SDK_TOKEN > key.json
gcloud auth activate-service-account --key-file=./key.json
gcloud config set project openebs-ci
export GOOGLE_APPLICATION_CREDENTIALS="./key.json"

echo "Deleting cluster"
ansible-playbook delete-k8s-cluster.yml

echo "Deleting VPC"
ansible-playbook delete-vpc.yml --extra-vars "project=openebs-ci"