#!/bin/bash
set -x 

derive_cluster_details_infra()
{
 path=$(pwd) 
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir ~/.kube 
 mkdir .kube-mayastor
 cp  $path/.kube/config ~/.kube/config
 cat $path/.kube/clusters > .kube-mayastor/clusters
}
 
setup_cluster_config_test()
{
 path=$(pwd)
  mkdir ~/.kube
  cp .kube-mayastor/config ~/.kube/config
  mkdir ~/logs
  cp .kube-mayastor/clusters ~/logs
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi 